name: rte_cubit
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.4.3

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_html: ^2.0.0
  intl: ^0.17.0
  adaptive_theme: ^2.0.0
  curved_navigation_bar: ^0.3.7
  qr_code_scanner: ^0.3.5
  syncfusion_flutter_barcodes: ^18.4.49
  flutter_restart: ^0.0.3
  get: ^4.1.1
  image_picker: ^0.7.3
  image_gallery_saver: ^1.6.9
  dio: ^4.0.0
  giphy_get: ^2.0.0-nullsafety.1
  cached_network_image: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/

flutter_intl:
  enabled: true
